/**
 * Tests for passkey evidence chains (HavenWebAuthnEvidence), single and batched.
 *
 * `evidence-vectors.json` is generated by the Python suite
 * (`tests/fixtures/evidence/gen_evidence_vectors.py`); this runtime must reach
 * the same result for every case (docs/specs/passkey-evidence.md §6).
 */

import { createHash, generateKeyPairSync, randomBytes, sign } from "node:crypto";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

import {
  buildWebAuthnEvidence,
  derToRaw,
  evidenceChallenge,
  payloadDigest,
  staticResolver,
  verifyEvidenceChain,
  verifyEvidenceForPayload,
  verifyInstructionEvidence,
  type EvidenceChainResult,
} from "../../../src/typescript/harbour/evidence.js";
import { b64urlEncode, buildBatch } from "../../../src/typescript/harbour/merkle.js";

const EVIDENCE_DIR = resolve(__dirname, "../../fixtures/evidence");
type Vectors = {
  now: number;
  trustAnchorDid: string;
  didDocuments: Record<string, Record<string, unknown>>;
  digests?: { input: Record<string, unknown>; digest: string }[];
  cases: {
    name: string;
    credential?: string;
    instruction?: Record<string, unknown>;
    evidence?: unknown;
    expected: Record<string, unknown>;
  }[];
};
const load = (name: string): Vectors =>
  JSON.parse(readFileSync(resolve(EVIDENCE_DIR, name), "utf-8"));

const VECTORS = load("evidence-vectors.json");

/** Failure details are free-form messages that differ per runtime; compare the rest. */
const withoutDetail = (expected: Record<string, unknown>, actual: EvidenceChainResult) => {
  const { detail: _detail, ...rest } = expected;
  return "detail" in actual ? { ...rest, detail: actual.detail } : rest;
};

const run = (v: Vectors, c: Vectors["cases"][number]): Promise<EvidenceChainResult> => {
  const options = {
    resolveDid: staticResolver(v.didDocuments),
    trustAnchorDid: v.trustAnchorDid,
    now: v.now,
  };
  return c.credential
    ? verifyEvidenceChain(c.credential, options)
    : verifyInstructionEvidence(c.instruction, c.evidence, options);
};

describe("vectors generated by Python", () => {
  for (const c of VECTORS.cases) {
    it(c.name, async () => {
      const result = await run(VECTORS, c);
      expect(result).toEqual(withoutDetail(c.expected, result));
    });
  }

  it("computes the payload digests", () => {
    for (const d of VECTORS.digests ?? []) {
      expect(payloadDigest(d.input)).toBe(d.digest);
      expect(evidenceChallenge(d.input)).toBe(d.digest);
    }
  });
});

// --- a fresh batch built in TypeScript ---------------------------------------

const b64 = (bytes: Uint8Array | Buffer) => b64urlEncode(new Uint8Array(bytes));
const sha256 = (data: Uint8Array | string) => createHash("sha256").update(data).digest();

function softPasskey() {
  const { privateKey, publicKey } = generateKeyPairSync("ec", { namedCurve: "P-256" });
  const jwk = publicKey.export({ format: "jwk" }) as Record<string, string>;
  const credentialId = b64(randomBytes(16));
  return {
    credentialId,
    jwk: { kty: "EC", crv: "P-256", x: jwk.x, y: jwk.y },
    assert(challenge: string, rpId: string, origin: string) {
      const clientData = Buffer.from(JSON.stringify({ type: "webauthn.get", challenge, origin }));
      const authData = Buffer.concat([sha256(rpId), Buffer.from([0x05, 0, 0, 0, 1])]);
      const signature = sign("sha256", Buffer.concat([authData, sha256(clientData)]), {
        key: privateKey,
        dsaEncoding: "der",
      });
      return {
        credentialId,
        authenticatorData: b64(authData),
        clientDataJSON: b64(clientData),
        signature: b64(signature),
      };
    },
  };
}

describe("batch approval in TypeScript", () => {
  // Reuse the Python tenant's DID documents with a new trust anchor passkey.
  const ta = VECTORS.trustAnchorDid;
  const docs = structuredClone(VECTORS.didDocuments);
  const taDoc = docs[ta] as Record<string, any>;
  const { rpId, origins } = taDoc.service[0].serviceEndpoint;
  const passkey = softPasskey();
  const vmId = `${ta}#passkey-${b64(sha256(Buffer.from(passkey.credentialId, "base64url")))}`;
  taDoc.verificationMethod.push({ id: vmId, type: "JsonWebKey", controller: ta, publicKeyJwk: passkey.jwk });
  taDoc.authentication.push(vmId);
  const options = { resolveDid: staticResolver(docs), trustAnchorDid: ta, now: VECTORS.now };
  const approver = { sub: "urn:uuid:00000000-0000-4000-8000-000000000002", memberOf: ta, role: "admin" as const };

  const orgPayload = (i: number) => ({
    iss: ta,
    sub: `did:web:did.harbour.example:participants:org-${i}`,
    iat: VECTORS.now - 86_400,
    exp: VECTORS.now + 86_400 * 700,
    jti: `urn:uuid:00000000-0000-4000-8000-00000000010${i}`,
    vct: "haven:OrganisationCredential",
    name: `Org ${i}`,
  });

  it("verifies every payload of a four-payload batch from one assertion", async () => {
    const payloads = [0, 1, 2, 3].map(orgPayload);
    const batch = buildBatch(payloads);
    const assertion = passkey.assert(batch.challenge, rpId, origins[0]);
    for (const [i, payload] of payloads.entries()) {
      const evidence = buildWebAuthnEvidence(assertion, { approver, merklePath: batch.paths[i] });
      expect(evidence.merklePath).toHaveLength(2);
      expect(await verifyEvidenceForPayload(payload, evidence, options)).toEqual({
        ok: true,
        approvers: [{ sub: approver.sub, memberOf: ta, via: "trust-anchor" }],
      });
    }
  });

  it("treats a batch of one as single-payload evidence", async () => {
    const payload = orgPayload(0);
    const batch = buildBatch([payload]);
    expect(batch.challenge).toBe(payloadDigest(payload));
    const evidence = buildWebAuthnEvidence(passkey.assert(batch.challenge, rpId, origins[0]), {
      approver,
      merklePath: batch.paths[0],
    });
    expect(evidence.merklePath).toBeUndefined();
    expect((await verifyEvidenceForPayload(payload, evidence, options)).ok).toBe(true);
  });

  it("rejects a payload outside the batch", async () => {
    const batch = buildBatch([orgPayload(0), orgPayload(1)]);
    const evidence = buildWebAuthnEvidence(passkey.assert(batch.challenge, rpId, origins[0]), {
      approver,
      merklePath: batch.paths[0],
    });
    const result = await verifyEvidenceForPayload(orgPayload(2), evidence, options);
    expect(result).toMatchObject({ ok: false, reason: "digest-mismatch", depth: 0 });
  });

  it("rejects a non-numeric version", async () => {
    const payload = orgPayload(0);
    const evidence = buildWebAuthnEvidence(passkey.assert(payloadDigest(payload), rpId, origins[0]), {
      approver,
    });
    expect((await verifyEvidenceForPayload(payload, evidence, options)).ok).toBe(true);
    const result = await verifyEvidenceForPayload(payload, { ...evidence, version: true }, options);
    expect(result).toMatchObject({ ok: false, reason: "malformed-evidence" });
  });

  it("rejects a payload that already carries evidence", async () => {
    const result = await verifyEvidenceForPayload({ evidence: [] }, {}, options);
    expect(result).toMatchObject({ ok: false, reason: "malformed-credential" });
  });
});

describe("derToRaw", () => {
  it("accepts minimal and zero-padded integers", () => {
    const minimal = Uint8Array.of(0x30, 0x07, 0x02, 0x01, 0x7f, 0x02, 0x02, 0x00, 0x80);
    const padded = Uint8Array.of(0x30, 0x08, 0x02, 0x02, 0x00, 0x7f, 0x02, 0x02, 0x00, 0x80);
    for (const der of [minimal, padded]) {
      const raw = derToRaw(der);
      expect(raw[31]).toBe(0x7f);
      expect(raw[63]).toBe(0x80);
    }
  });

  it("rejects trailing bytes and bad tags", () => {
    expect(() => derToRaw(Uint8Array.of(0x31, 0x00))).toThrow();
    expect(() =>
      derToRaw(Uint8Array.of(0x30, 0x06, 0x02, 0x01, 0x01, 0x02, 0x01, 0x01, 0x00)),
    ).toThrow();
  });
});
