import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  buildBatch,
  computeLeaf,
  b64urlEncode,
  b64urlDecode,
  merkleRoot,
  inclusionProof,
  verifyInclusion,
} from "../../../src/typescript/harbour/merkle.js";

// The vectors are generated by the Python implementation; this suite proves the
// TypeScript Merkle construction is byte-identical (shared RFC 8785 / JCS).
const VECTORS = JSON.parse(
  readFileSync(
    resolve(__dirname, "../../fixtures/batched-evidence-vectors.json"),
    "utf-8",
  ),
);

describe("merkle (cross-runtime parity with Python vectors)", () => {
  it("reproduces the N=4 root, leaves, and proofs byte-for-byte", () => {
    const n4 = VECTORS.batch_n4;
    const fresh = buildBatch(n4.credentials);
    expect(fresh.root).toBe(n4.root);
    expect(fresh.leaves).toEqual(n4.leaves);
    expect(fresh.proofs).toEqual(n4.proofs);
  });

  it("every committed proof folds to the root", () => {
    const n4 = VECTORS.batch_n4;
    const root = b64urlDecode(n4.root);
    for (let i = 0; i < n4.credentials.length; i++) {
      expect(verifyInclusion(computeLeaf(n4.credentials[i]), n4.proofs[i], root)).toBe(
        true,
      );
    }
  });

  it("matches the N=1 degenerate batch (empty path, root == leaf)", () => {
    const n1 = VECTORS.batch_n1_degenerate;
    const fresh = buildBatch([n1.credential]);
    expect(fresh.proofs[0]).toEqual([]);
    expect(fresh.root).toBe(n1.root);
    expect(fresh.root).toBe(fresh.leaves[0]);
  });

  it("the leaf excludes evidence and proof (disclosure-invariant)", () => {
    const inv = VECTORS.evidence_invariance;
    const withEvidence = VECTORS.batch_n4.credentials[0];
    const without = { ...withEvidence };
    delete without.evidence;
    expect(b64urlEncode(computeLeaf(withEvidence))).toBe(inv.leaf_with_evidence);
    expect(b64urlEncode(computeLeaf(without))).toBe(b64urlEncode(computeLeaf(withEvidence)));
  });

  it("rejects tampered leaf, swapped position, and wrong root", () => {
    const n4 = VECTORS.batch_n4;
    const root = b64urlDecode(n4.root);
    const leaf = computeLeaf(n4.credentials[0]);

    const tampered = Buffer.from(leaf);
    tampered[0] ^= 0x01;
    expect(verifyInclusion(tampered, n4.proofs[0], root)).toBe(false);

    const swapped = n4.proofs[0].map((s: { hash: string; position: string }) => ({
      ...s,
      position: s.position === "right" ? "left" : "right",
    }));
    expect(verifyInclusion(leaf, swapped, root)).toBe(false);

    const wrongRoot = Buffer.from(root);
    wrongRoot[0] ^= 0x01;
    expect(verifyInclusion(leaf, n4.proofs[0], wrongRoot)).toBe(false);
  });

  it("round-trips arbitrary batch sizes", () => {
    for (const n of [1, 2, 3, 5, 8, 17]) {
      const creds = Array.from({ length: n }, (_, i) => ({
        id: `urn:${i}`,
        issuer: "did:ethr:0x14a34:0xabc",
      }));
      const leaves = creds.map(computeLeaf);
      const root = merkleRoot(leaves);
      for (let i = 0; i < n; i++) {
        expect(verifyInclusion(leaves[i], inclusionProof(leaves, i), root)).toBe(true);
      }
    }
  });
});
