/**
 * Verify signed example artifacts generated by ``story-sign.ts``.
 *
 * Mirrors the Python ``credentials.verify_signed_examples`` pipeline: validates
 * the ``examples/signed/`` and ``examples/gaiax/signed/`` output using the real
 * harbour TypeScript verification functions.
 *
 * When multi-role keys are available, each JWT is verified with the key that
 * matches its ``kid`` header — proving that different roles really did sign
 * different artifacts.
 */

import { readFileSync, readdirSync, existsSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  importP256PublicKey,
  verifyVcJose,
  verifyVpJose,
  type JWK,
} from "./index.js";

// ---------------------------------------------------------------------------
// Path helpers
// ---------------------------------------------------------------------------

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

function findRepoRoot(): string {
  let current = resolve(__dirname);
  while (current !== dirname(current)) {
    // Look for the harbour-credentials repo specifically (has tests/fixtures/keys)
    try {
      readdirSync(join(current, "tests", "fixtures", "keys"));
      return current;
    } catch {
      // not found, go up
    }
    current = dirname(current);
  }
  return process.cwd();
}

const REPO_ROOT = findRepoRoot();
const KEYS_DIR = join(REPO_ROOT, "tests", "fixtures", "keys");

// ---------------------------------------------------------------------------
// Role DID mapping and key resolution
// ---------------------------------------------------------------------------

interface RoleDIDMapping {
  [role: string]: {
    did_ethr: string;
    did_key: string;
    eth_addr: string;
  };
}

const ROLE_FILES: Record<string, string> = {
  "trust-anchor": "trust-anchor.p256.json",
  haven: "haven.p256.json",
  company: "company.p256.json",
  employee: "employee.p256.json",
  ascs: "ascs.p256.json",
};

async function buildKeyResolver(): Promise<{
  resolve: (kid: string | undefined) => Promise<CryptoKey>;
  roleForKid: (kid: string | undefined) => string;
}> {
  const mapping: RoleDIDMapping = JSON.parse(
    readFileSync(join(KEYS_DIR, "role-did-mapping.json"), "utf-8"),
  );

  const kidToPublicKey = new Map<string, CryptoKey>();
  const kidToRole = new Map<string, string>();

  for (const [role, filename] of Object.entries(ROLE_FILES)) {
    const jwk: JWK = JSON.parse(
      readFileSync(join(KEYS_DIR, filename), "utf-8"),
    );
    const publicKey = await importP256PublicKey(jwk);
    const did = mapping[role]?.did_ethr;
    if (!did) continue;

    const kid = `${did}#controller`;
    kidToPublicKey.set(kid, publicKey);
    kidToRole.set(kid, role);
  }

  // Fallback key
  const fallbackJwk: JWK = JSON.parse(
    readFileSync(join(KEYS_DIR, "test-keypair-p256.json"), "utf-8"),
  );
  const fallbackPublicKey = await importP256PublicKey(fallbackJwk);

  return {
    resolve: async (kid: string | undefined) => {
      if (kid && kidToPublicKey.has(kid)) return kidToPublicKey.get(kid)!;
      return fallbackPublicKey;
    },
    roleForKid: (kid: string | undefined) => {
      if (kid && kidToRole.has(kid)) return kidToRole.get(kid)!;
      return "fallback";
    },
  };
}

// ---------------------------------------------------------------------------
// JWT header extraction (no verification)
// ---------------------------------------------------------------------------

function jwtKid(token: string): string | undefined {
  const headerB64 = token.split(".")[0];
  const padded = headerB64 + "=".repeat((4 - (headerB64.length % 4)) % 4);
  const header = JSON.parse(
    Buffer.from(padded, "base64url").toString("utf-8"),
  );
  return header.kid;
}

// ---------------------------------------------------------------------------
// Discover signed directories and credentials
// ---------------------------------------------------------------------------

function discoverSignedDirs(): string[] {
  const candidates = [
    join(REPO_ROOT, "examples", "signed"),
    join(REPO_ROOT, "examples", "gaiax", "signed"),
  ];
  return candidates.filter((d) => existsSync(d));
}

function iterSignedCredentials(signedDir: string): string[] {
  return readdirSync(signedDir)
    .filter((f) => f.endsWith(".jwt") && !f.includes(".evidence-vp."))
    .sort()
    .map((f) => join(signedDir, f));
}

// ---------------------------------------------------------------------------
// Type assertion
// ---------------------------------------------------------------------------

function assertHasType(
  payload: Record<string, unknown>,
  expectedType: string,
  source: string,
): void {
  let types = payload["type"];
  if (typeof types === "string") types = [types];
  if (!Array.isArray(types) || !types.includes(expectedType)) {
    throw new Error(
      `${source} does not contain expected type '${expectedType}': ${JSON.stringify(types)}`,
    );
  }
}

// ---------------------------------------------------------------------------
// Verify a signed directory
// ---------------------------------------------------------------------------

interface VerificationCounts {
  credentials: number;
  evidencePresentations: number;
  nestedCredentials: number;
}

async function verifySignedDir(
  signedDir: string,
  resolver: {
    resolve: (kid: string | undefined) => Promise<CryptoKey>;
    roleForKid: (kid: string | undefined) => string;
  },
): Promise<VerificationCounts> {
  const counts: VerificationCounts = {
    credentials: 0,
    evidencePresentations: 0,
    nestedCredentials: 0,
  };

  const signedCredentials = iterSignedCredentials(signedDir);
  if (signedCredentials.length === 0) {
    throw new Error(`No signed VC JWTs found in ${signedDir}`);
  }

  for (const jwtPath of signedCredentials) {
    const vcJwt = readFileSync(jwtPath, "utf-8").trim();
    const kid = jwtKid(vcJwt);
    const pub = await resolver.resolve(kid);
    const role = resolver.roleForKid(kid);

    const vcPayload = await verifyVcJose(vcJwt, pub);
    assertHasType(
      vcPayload,
      "VerifiableCredential",
      jwtPath,
    );
    counts.credentials++;
    const jwtName = jwtPath.split(/[\\/]/).pop()!;
    console.log(`    ✓ ${jwtName} (signed by: ${role})`);

    // Check for evidence VP
    const evJwtPath = jwtPath.replace(/\.jwt$/, ".evidence-vp.jwt");
    if (!existsSync(evJwtPath)) continue;

    const vpJwt = readFileSync(evJwtPath, "utf-8").trim();
    const vpKid = jwtKid(vpJwt);
    const vpPub = await resolver.resolve(vpKid);
    const vpRole = resolver.roleForKid(vpKid);

    const vpPayload = await verifyVpJose(vpJwt, vpPub);
    assertHasType(
      vpPayload,
      "VerifiablePresentation",
      evJwtPath,
    );
    counts.evidencePresentations++;
    const evName = evJwtPath.split(/[\\/]/).pop()!;
    console.log(`    ✓ ${evName} (signed by: ${vpRole})`);

    // Verify embedded VP matches
    const evidence = (vcPayload["evidence"] as Record<string, unknown>[]) ?? [];
    const embeddedVps = evidence
      .filter((e) => typeof e === "object" && e !== null)
      .map((e) => e["verifiablePresentation"])
      .filter((v) => typeof v === "string");
    if (!embeddedVps.includes(vpJwt)) {
      throw new Error(
        `${evJwtPath} was not embedded in ${jwtPath} evidence chain`,
      );
    }

    // Verify inner VCs in the VP
    const innerVcs =
      (vpPayload["verifiableCredential"] as unknown[]) ?? [];
    for (const inner of innerVcs) {
      if (
        typeof inner === "string" &&
        inner.split(".").length === 3
      ) {
        const innerKid = jwtKid(inner);
        const innerPub = await resolver.resolve(innerKid);
        const innerRole = resolver.roleForKid(innerKid);

        const innerPayload = await verifyVcJose(inner, innerPub);
        assertHasType(
          innerPayload,
          "VerifiableCredential",
          `inner VC in ${evJwtPath}`,
        );
        counts.nestedCredentials++;
        console.log(`      ✓ inner VC (signed by: ${innerRole})`);
      }
    }
  }

  return counts;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const resolver = await buildKeyResolver();

  const signedDirs = discoverSignedDirs();
  if (signedDirs.length === 0) {
    throw new Error(
      "No signed example directories found. Run `make story sign` or `make story ts` first.",
    );
  }

  const total: VerificationCounts = {
    credentials: 0,
    evidencePresentations: 0,
    nestedCredentials: 0,
  };

  for (const signedDir of signedDirs) {
    console.log(`  Verifying ${signedDir}/`);
    const counts = await verifySignedDir(signedDir, resolver);
    total.credentials += counts.credentials;
    total.evidencePresentations += counts.evidencePresentations;
    total.nestedCredentials += counts.nestedCredentials;
  }

  console.log(
    `\nDone: ${total.credentials} credential JWT(s), ` +
      `${total.evidencePresentations} evidence VP JWT(s), ` +
      `${total.nestedCredentials} nested VC JWT(s) verified`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
