"""Verify signed example artifacts generated by ``credentials.example_signer``.

This script validates the ignored ``examples/signed/`` and
``examples/gaiax/signed/`` output folders using the real Harbour verification
functions. It is intended for end-to-end storyline runs driven by ``make``.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from credentials.example_signer import load_test_p256_keypair
from harbour.verifier import verify_vc_jose, verify_vp_jose


@dataclass
class VerificationCounts:
    """Summary counters for verified example artifacts."""

    credentials: int = 0
    evidence_presentations: int = 0
    nested_credentials: int = 0


def _find_repo_root() -> Path:
    current = Path(__file__).resolve().parent
    while current != current.parent:
        if (current / ".git").is_dir() or (current / "submodules").is_dir():
            return current
        current = current.parent
    return Path.cwd()


def _discover_signed_dirs(repo_root: Path) -> list[Path]:
    candidates = [
        repo_root / "examples" / "signed",
        repo_root / "examples" / "gaiax" / "signed",
    ]
    return [path for path in candidates if path.is_dir()]


def _iter_signed_credentials(signed_dir: Path) -> list[Path]:
    return sorted(
        path for path in signed_dir.glob("*.jwt") if ".evidence-vp." not in path.name
    )


def _assert_has_type(payload: dict, expected_type: str, source: Path) -> None:
    types = payload.get("type", [])
    if isinstance(types, str):
        types = [types]
    if expected_type not in types:
        raise RuntimeError(
            f"{source} does not contain expected type {expected_type!r}: {types!r}"
        )


def verify_signed_dir(signed_dir: Path, public_key) -> VerificationCounts:
    counts = VerificationCounts()
    signed_credentials = _iter_signed_credentials(signed_dir)
    if not signed_credentials:
        raise RuntimeError(f"No signed VC JWTs found in {signed_dir}")

    for jwt_path in signed_credentials:
        vc_jwt = jwt_path.read_text(encoding="utf-8").strip()
        vc_payload = verify_vc_jose(vc_jwt, public_key)
        _assert_has_type(vc_payload, "VerifiableCredential", jwt_path)
        counts.credentials += 1

        evidence_jwt_path = jwt_path.with_name(f"{jwt_path.stem}.evidence-vp.jwt")
        if not evidence_jwt_path.exists():
            continue

        vp_jwt = evidence_jwt_path.read_text(encoding="utf-8").strip()
        vp_payload = verify_vp_jose(vp_jwt, public_key)
        _assert_has_type(vp_payload, "VerifiablePresentation", evidence_jwt_path)
        counts.evidence_presentations += 1

        embedded_vps = [
            evidence.get("verifiablePresentation")
            for evidence in vc_payload.get("evidence", [])
            if isinstance(evidence, dict)
        ]
        if vp_jwt not in embedded_vps:
            raise RuntimeError(
                f"{evidence_jwt_path} was not embedded in {jwt_path} evidence chain"
            )

        for inner in vp_payload.get("verifiableCredential", []):
            if isinstance(inner, str) and inner.count(".") == 2:
                inner_payload = verify_vc_jose(inner, public_key)
                _assert_has_type(
                    inner_payload, "VerifiableCredential", evidence_jwt_path
                )
                counts.nested_credentials += 1

    return counts


def main() -> None:
    repo_root = _find_repo_root()
    _, public_key = load_test_p256_keypair()
    signed_dirs = _discover_signed_dirs(repo_root)
    if not signed_dirs:
        raise RuntimeError(
            "No signed example directories found. Run `make story-sign` first."
        )

    total = VerificationCounts()
    for signed_dir in signed_dirs:
        counts = verify_signed_dir(signed_dir, public_key)
        total.credentials += counts.credentials
        total.evidence_presentations += counts.evidence_presentations
        total.nested_credentials += counts.nested_credentials
        print(
            f"Verified {counts.credentials} credential JWT(s), "
            f"{counts.evidence_presentations} evidence VP JWT(s), and "
            f"{counts.nested_credentials} nested VC JWT(s) in {signed_dir}"
        )

    print(
        "Done: "
        f"{total.credentials} credential JWT(s), "
        f"{total.evidence_presentations} evidence VP JWT(s), "
        f"{total.nested_credentials} nested VC JWT(s) verified"
    )


if __name__ == "__main__":
    main()
